### ISSUE TITLE
TypeError: server.views is not a function

### ISSUE THREAD

**Issue by e72575f3** [nesive/hapi-mailer#19]
Using the example code:
```
var options = {
    transport: {
        service: 'Gmail',
        auth: {
            user: 'example@gmail.com',
            pass: 'password'
        }
    },
    views: {
        engines: {
            html: {
                module: Handlebars.create(),
                path: Path.join(__dirname, 'lib/views/emails')
            }
        }
    }
};
```

throws the error
```
/node_modules/hapi-mailer/lib/index.js:46
        server.views(config.views);
               ^

TypeError: server.views is not a function
```

Is hapi-mailer the recommended mailer or is it fragile and should nodemailer be used directly for production systems?

**Comment by gergoerdosi** [comment]
It's up to you which one you decide to use. We use hapi-mailer on production for a long time and it works fine. You get the error because the code hasn't been updated to the latest version of hapi. I will release a new, updated version later this week. Till then, try to install and register the vision module, it should solve the error.

**Comment by e72575f3** [comment]
Thank you for the fast response, looking forward to the updated example. Do you have more code / real world examples for hapi-mailer ?
